### ISSUE TITLE
2 enum values missing from Xero XSDs

### ISSUE THREAD

**Issue by evan-williams** [XeroAPI/XeroAPI-Schemas#14]
HI guys - just a small issue we have found - the XSDs here on Git hub are missing:

1. AddressType enum value for DELIVERY (we have received API responses with this value on and this breaks the serialisation).
2. Same issue with TaxStatus value of ARCHIVED.
3. We also had to add includes on the Payment message for Contact.xsd and LineItem.xsd to fix failing serialisation issues.

We have worked around these issue with our local copies of the XSD's and the resulting C# classes but it would be great if the XSD copies here could be updated too so we don't lose these tweaks in future.

**Comment by SidneyAllen** [comment]
Xero missing types have been added
