### ISSUE TITLE
Missing BankTransactionType

### ISSUE THREAD

**Issue by riankruger** [XeroAPI/XeroAPI-Schemas#31]
Hi

There are a number of BankTransactionTypes that do not appear on the XSD:

RECEIVE-OVERPAYMENT
RECEIVE-PREPAYMENT
SPEND-OVERPAYMENT
SPEND-PREPAYMENT
RECEIVE-TRANSFER
SPEND-TRANSFER

Could you please add them?

Thanks

**Comment by SidneyAllen** [comment]
added missing types
