### ISSUE TITLE
minOccurs="0".*nillable="true" matches 52 lines across all .xsd docs.

### ISSUE THREAD

**Issue by dtbullock** [XeroAPI/XeroAPI-Schemas#33]
If it's optional (`minOccurs="0"`), it's just not *necessary* to also make it `nillable`.  If code doing databinding/marshalling doesn't have a value to bind, it will always opt to *omit* the element from the generated XML doc.

So let's get rid of `nillable` for that case.

That only leaves a handful of cases, where some non-optional elements also have `nillable`.  This essentially says, 'the element is required, but it is allowed to be empty'.  I count 6 in total:

4:

CreditNote/Date  ... but you can create a DRAFT credit  without a date, so minOccurs="1" is wrong
CreditNote/Total ... but you can create a DRAFT credit without a total, so minOccurs="1" is wrong
TaxRate/DisplayTaxRate ... but you can POST without this, so minOccurs="1" is wrong
TaxRate/EffectiveTaxRate ... but you can POST without this, so minOccurs="1" is wrong

So let's change them to `minOccurs="0"` and dispense with `nillable` for these.

2:
Journal/JournalDate ... ... but surely for any given Journal with GET, it'll have a date and the server won't ever need to fudge? `nillable` is wrong here
Journal/CreatedDateUTC ... but surely for any given Journal with GET, it'll have a timestamp and the server won't ever need to fudge? `nillable` is wrong here

And that will neatly take care of all the use of 'nillable' in the entire schema

**Comment by dtbullock** [comment]
I am really finding the schemas to be of questionable quality and usefulness.

**Comment by SidneyAllen** [comment]
I've completed a review of the Xero XSDs and have addressed many of the outstanding issues and added support for any missing objects.  They now more accurately reflect our API docs.
