### ISSUE TITLE
Missing Curaçao in list of countries

### ISSUE THREAD

**Issue by ScopeSebastian** [XeroAPI/XeroAPI-Schemas#50]
List of countries should contain Curaçao:

`
<xs:enumeration value="CW">
       <xs:annotation>
           <xs:documentation>CURAÇAO</xs:documentation>
       </xs:annotation>
</xs:enumeration>
`

**Comment by GuiSim** [comment]
Looks like this has been fixed.
https://github.com/XeroAPI/XeroAPI-Schemas/commit/76719654974fb0d23db8c5bd22c7a482b47a3b6a

Is there a reason why this is not closed?
